//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int SchoolId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
