//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringsTestConsumer.Console.IISServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISServiceReference1.IServiceStringsTest")]
    public interface IServiceStringsTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringsTest/FindStringRepetitionInTargetString", ReplyAction="http://tempuri.org/IServiceStringsTest/FindStringRepetitionInTargetStringResponse" +
            "")]
        int FindStringRepetitionInTargetString(string toCheck, string targetString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringsTest/FindStringRepetitionInTargetString", ReplyAction="http://tempuri.org/IServiceStringsTest/FindStringRepetitionInTargetStringResponse" +
            "")]
        System.Threading.Tasks.Task<int> FindStringRepetitionInTargetStringAsync(string toCheck, string targetString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStringsTestChannel : StringsTestConsumer.Console.IISServiceReference1.IServiceStringsTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStringsTestClient : System.ServiceModel.ClientBase<StringsTestConsumer.Console.IISServiceReference1.IServiceStringsTest>, StringsTestConsumer.Console.IISServiceReference1.IServiceStringsTest {
        
        public ServiceStringsTestClient() {
        }
        
        public ServiceStringsTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStringsTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStringsTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStringsTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int FindStringRepetitionInTargetString(string toCheck, string targetString) {
            return base.Channel.FindStringRepetitionInTargetString(toCheck, targetString);
        }
        
        public System.Threading.Tasks.Task<int> FindStringRepetitionInTargetStringAsync(string toCheck, string targetString) {
            return base.Channel.FindStringRepetitionInTargetStringAsync(toCheck, targetString);
        }
    }
}
