//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Year { get; set; }
        public string Genre { get; set; }
        public int AlbumId { get; set; }
        public int ArtistId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
